-- ============================================================
-- Seed: Daily Bible Verses (100 verses for recovery)
-- ============================================================

INSERT INTO daily_verses (reference, text, theme) VALUES
('Psalm 46:1', 'God is our refuge and strength, an ever-present help in trouble.', 'strength'),
('Romans 8:28', 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.', 'hope'),
('Philippians 4:13', 'I can do all this through him who gives me strength.', 'strength'),
('Isaiah 41:10', 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.', 'comfort'),
('1 Corinthians 10:13', 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.', 'temptation'),
('James 4:7', 'Submit yourselves, then, to God. Resist the devil, and he will flee from you.', 'temptation'),
('Galatians 5:1', 'It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.', 'freedom'),
('John 8:36', 'So if the Son sets you free, you will be free indeed.', 'freedom'),
('Romans 6:14', 'For sin shall no longer be your master, because you are not under the law, but under grace.', 'freedom'),
('2 Corinthians 5:17', 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!', 'renewal'),
('Lamentations 3:22-23', 'Because of the LORD''s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.', 'renewal'),
('Psalm 51:10', 'Create in me a pure heart, O God, and renew a steadfast spirit within me.', 'renewal'),
('Romans 12:2', 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.', 'transformation'),
('Ephesians 4:22-24', 'You were taught, with regard to your former way of life, to put off your old self, which is being corrupted by its deceitful desires; to be made new in the attitude of your minds; and to put on the new self, created to be like God in true righteousness and holiness.', 'transformation'),
('Psalm 34:18', 'The LORD is close to the brokenhearted and saves those who are crushed in spirit.', 'comfort'),
('Matthew 11:28', 'Come to me, all you who are weary and burdened, and I will give you rest.', 'comfort'),
('Isaiah 43:2', 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.', 'comfort'),
('Psalm 23:4', 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.', 'comfort'),
('Romans 8:37', 'No, in all these things we are more than conquerors through him who loved us.', 'victory'),
('1 John 4:4', 'You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world.', 'victory'),
('Revelation 12:11', 'They triumphed over him by the blood of the Lamb and by the word of their testimony.', 'victory'),
('Psalm 18:2', 'The LORD is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge, my shield and the horn of my salvation, my stronghold.', 'strength'),
('Isaiah 40:31', 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.', 'strength'),
('Ephesians 6:11', 'Put on the full armor of God, so that you can take your stand against the devil''s schemes.', 'temptation'),
('1 Peter 5:8', 'Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour.', 'temptation'),
('Hebrews 4:15', 'For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are—yet he did not sin.', 'temptation'),
('Hebrews 12:1', 'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us.', 'perseverance'),
('James 1:12', 'Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life that the Lord has promised to those who love him.', 'perseverance'),
('Philippians 3:14', 'I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.', 'perseverance'),
('Psalm 40:1-2', 'I waited patiently for the LORD; he turned to me and heard my cry. He lifted me out of the slimy pit, out of the mud and mire; he set my feet on a rock and gave me a firm place to stand.', 'hope'),
('Jeremiah 29:11', 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.', 'hope'),
('Romans 15:13', 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.', 'hope'),
('Psalm 119:9', 'How can a young person stay on the path of purity? By living according to your word.', 'purity'),
('Matthew 5:8', 'Blessed are the pure in heart, for they will see God.', 'purity'),
('1 Thessalonians 4:3', 'It is God''s will that you should be sanctified: that you should avoid sexual immorality.', 'purity'),
('Job 31:1', 'I made a covenant with my eyes not to look lustfully at a young woman.', 'purity'),
('Psalm 101:3', 'I will not look with approval on anything that is vile.', 'purity'),
('Proverbs 4:23', 'Above all else, guard your heart, for everything you do flows from it.', 'wisdom'),
('Proverbs 3:5-6', 'Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.', 'wisdom'),
('James 1:5', 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.', 'wisdom'),
('1 Corinthians 6:19-20', 'Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own; you were bought at a price. Therefore honor God with your bodies.', 'purity'),
('Romans 13:14', 'Rather, clothe yourselves with the Lord Jesus Christ, and do not think about how to gratify the desires of the flesh.', 'temptation'),
('Colossians 3:2', 'Set your minds on things above, not on earthly things.', 'renewal'),
('2 Timothy 2:22', 'Flee the evil desires of youth and pursue righteousness, faith, love and peace, along with those who call on the Lord out of a pure heart.', 'purity'),
('Psalm 86:5', 'You, Lord, are forgiving and good, abounding in love to all who call to you.', 'forgiveness'),
('1 John 1:9', 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.', 'forgiveness'),
('Micah 7:19', 'You will again have compassion on us; you will tread our sins underfoot and hurl all our iniquities into the depths of the sea.', 'forgiveness'),
('Psalm 103:12', 'As far as the east is from the west, so far has he removed our transgressions from us.', 'forgiveness'),
('Isaiah 1:18', 'Come now, let us settle the matter. Though your sins are like scarlet, they shall be as white as snow; though they are red as crimson, they shall be like wool.', 'forgiveness'),
('Romans 8:1', 'Therefore, there is now no condemnation for those who are in Christ Jesus.', 'forgiveness'),
('Ephesians 1:7', 'In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God''s grace.', 'forgiveness'),
('Hebrews 10:22', 'Let us draw near to God with a sincere heart and with the full assurance that faith brings, having our hearts sprinkled to cleanse us from a guilty conscience.', 'forgiveness'),
('Galatians 6:1', 'Brothers and sisters, if someone is caught in a sin, you who live by the Spirit should restore that person gently. But watch yourselves, or you also may be tempted.', 'community'),
('Proverbs 27:17', 'As iron sharpens iron, so one person sharpens another.', 'community'),
('Hebrews 10:24-25', 'And let us consider how we may spur one another on toward love and good deeds, not giving up meeting together, as some are in the habit of doing, but encouraging one another.', 'community'),
('Ecclesiastes 4:9-10', 'Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up. But pity anyone who falls and has no one to help them up.', 'community'),
('James 5:16', 'Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective.', 'community'),
('Matthew 18:20', 'For where two or three gather in my name, there am I with them.', 'community'),
('Psalm 55:22', 'Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken.', 'trust'),
('Proverbs 3:5', 'Trust in the LORD with all your heart and lean not on your own understanding.', 'trust'),
('Nahum 1:7', 'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.', 'trust'),
('Psalm 37:5', 'Commit your way to the LORD; trust in him and he will do this.', 'trust'),
('Isaiah 26:3', 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.', 'peace'),
('John 14:27', 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.', 'peace'),
('Philippians 4:6-7', 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.', 'peace'),
('Romans 5:1', 'Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.', 'peace'),
('Psalm 32:1', 'Blessed is the one whose transgressions are forgiven, whose sins are covered.', 'blessing'),
('Numbers 6:24-26', 'The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you; the LORD turn his face toward you and give you peace.', 'blessing'),
('Deuteronomy 31:8', 'The LORD himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged.', 'courage'),
('Joshua 1:9', 'Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.', 'courage'),
('2 Timothy 1:7', 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.', 'courage'),
('Psalm 27:1', 'The LORD is my light and my salvation—whom shall I fear? The LORD is the stronghold of my life—of whom shall I be afraid?', 'courage'),
('Hebrews 13:5', 'Keep your lives free from the love of money and be content with what you have, because God has said, Never will I leave you; never will I forsake you.', 'trust'),
('Psalm 145:18', 'The LORD is near to all who call on him, to all who call on him in truth.', 'trust'),
('Romans 8:38-39', 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.', 'love'),
('John 3:16', 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.', 'love'),
('1 John 4:18', 'There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love.', 'love'),
('Zephaniah 3:17', 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.', 'love'),
('1 Peter 1:13', 'Therefore, with minds that are alert and fully sober, set your hope on the grace to be brought to you when Jesus Christ is revealed at his coming.', 'hope'),
('Colossians 1:13', 'For he has rescued us from the dominion of darkness and brought us into the kingdom of the Son he loves.', 'freedom'),
('Psalm 107:13-14', 'Then they cried to the LORD in their trouble, and he saved them from their distress. He brought them out of darkness, the utter darkness, and broke away their chains.', 'freedom'),
('Luke 4:18', 'The Spirit of the Lord is on me, because he has anointed me to proclaim good news to the poor. He has sent me to proclaim freedom for the prisoners and recovery of sight for the blind, to set the oppressed free.', 'freedom'),
('Acts 3:19', 'Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord.', 'renewal'),
('Isaiah 61:3', 'To bestow on them a crown of beauty instead of ashes, the oil of joy instead of mourning, and a garment of praise instead of a spirit of despair.', 'renewal'),
('Ezekiel 36:26', 'I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh.', 'transformation'),
('2 Corinthians 4:16', 'Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day.', 'perseverance'),
('Romans 5:3-4', 'Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope.', 'perseverance'),
('Psalm 46:10', 'He says, Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.', 'peace'),
('Proverbs 28:13', 'Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy.', 'forgiveness'),
('Matthew 5:3', 'Blessed are the poor in spirit, for theirs is the kingdom of heaven.', 'blessing'),
('Psalm 34:8', 'Taste and see that the LORD is good; blessed is the one who takes refuge in him.', 'blessing'),
('Ephesians 3:20', 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.', 'hope'),
('Philippians 1:6', 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.', 'hope'),
('Psalm 71:20', 'Though you have made me see troubles, many and bitter, you will restore my life again; from the depths of the earth you will again bring me up.', 'hope'),
('Joel 2:25', 'I will repay you for the years the locusts have eaten.', 'restoration'),
('Isaiah 43:19', 'See, I am doing a new thing! Now it springs up; do you not perceive it? I am making a way in the wilderness and streams in the wasteland.', 'renewal'),
('Psalm 30:5', 'Weeping may stay for the night, but rejoicing comes in the morning.', 'hope');
